# Generated by Django 4.1.7 on 2024-02-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SAV', 'Saving'), ('MUT', 'Mutual Fund'), ('EXP', 'Expense'), ('CC', 'Credit Card'), ('LOA', 'Loan'), ('WAL', 'Cash Wallet'), ('FAM', 'Family')], max_length=3),
        ),
    ]
