# Generated by Django 4.1.7 on 2023-07-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_remove_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='extra_footer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='extra_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('customer', 'invoice_number')},
        ),
    ]
