# Generated by Django 4.1.7 on 2024-02-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_invoice_extra_footer_invoice_extra_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the Business')),
                ('address', models.TextField()),
                ('gst_number', models.CharField(max_length=16, verbose_name='GST Number')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Single line description added above the list of items', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='sac_code',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
